[package]
name = "ksynth"
version = "0.11.5"
authors = ["Jere Käpyaho <2261936+jerekapyaho@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/coniferprod/ksynth-rs"
description = """
Patch manipulation for Kawai digital synths
"""

[dependencies]
num_enum = "0.5.7"
bit = "0.1.1"
lazy_static = "1.4.0"
log = "0.4.17"
num = "0.4.0"
rand = "0.8.5"
