[package]
name = "ksynth"
version = "0.7.3"
authors = ["Jere Käpyaho <2261936+jerekapyaho@users.noreply.github.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/coniferprod/ksynth-rs"
description = """
Patch manipulation for Kawai digital synths
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.1"
bit = "0.1.1"
lazy_static = "1.4.0"
log = "0.4.14"
